<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
   <xacro:include filename="$(find rover0_description)/urdf/rover0_description_common.urdf.xacro" />
   <xacro:include filename="$(find rover0_description)/urdf/rover0_description_lidar.urdf.xacro" />
   <xacro:include filename="$(find rover0_description)/urdf/rover0_description_imu.urdf.xacro" />
   <xacro:include filename="$(find rover0_description)/urdf/rover0_description_camera.urdf.xacro" />
   <xacro:include filename="$(find rover0_description)/urdf/rover0_description_wheel.urdf.xacro" />

   <xacro:property name="base_width" value="0.14" />
   <xacro:property name="base_length" value="0.255" />
   <xacro:property name="base_height" value="0.058" />
   <xacro:property name="base_mass" value="0.3" />

   <xacro:property name="wheel_ygap" value="0.01" />
   <xacro:property name="wheel_x_off" value="0.055" />
   <xacro:property name="wheel_y_off" value="${base_width/2 + wheel_ygap}" />
   <xacro:property name="wheel_z_off" value="0.021" />
   <xacro:property name="lidar_x_off" value="-0.078" />
   <xacro:property name="camera_x_off" value="0.11" />
   <xacro:property name="camera_y_off" value="0.0" />
   <xacro:property name="camera_z_off" value="0.015" />

  <xacro:macro name="rover0" params="prefix">
    <xacro:macro name="base">
        <link name="${prefix}base_link">
          <visual>
            <geometry>
              <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange"/>
          </visual>

          <collision>
            <geometry>
              <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
          </collision>

          <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
        </link>

        <link name="${prefix}base_footprint" />
        <joint name="${prefix}base_joint" type="fixed">
          <parent link="${prefix}base_footprint" />
          <child link="${prefix}base_link" />
          <origin xyz="0.0 0.0 ${(wheel_radius+wheel_z_off)}" rpy="0 0 0" />
        </joint>
    </xacro:macro>
    <xacro:base/>

    <xacro:wheel prefix="front_left" parent="${prefix}base_link" x_reflect="1" y_reflect="1" x_off="${wheel_x_off}" y_off="${wheel_y_off}" z_off="${wheel_z_off}"/>
    <xacro:wheel prefix="front_right" parent="${prefix}base_link"  x_reflect="1" y_reflect="-1" x_off="${wheel_x_off}" y_off="${wheel_y_off}" z_off="${wheel_z_off}"/>
    <xacro:wheel prefix="rear_left" parent="${prefix}base_link" x_reflect="-1" y_reflect="1" x_off="${wheel_x_off}" y_off="${wheel_y_off}" z_off="${wheel_z_off}"/>
    <xacro:wheel prefix="rear_right" parent="${prefix}base_link" x_reflect="-1" y_reflect="-1" x_off="${wheel_x_off}" y_off="${wheel_y_off}" z_off="${wheel_z_off}"/>
    <xacro:lidar prefix="rover0" parent="${prefix}base_link" base_height="${base_height}" x_off="${lidar_x_off}" />
    <xacro:imu prefix="rover0" parent="${prefix}base_link" x_off="0" y_off="0.0125" z_off="0.008"/>
    <xacro:camera prefix="rover0" parent="${prefix}base_link" x_off="${camera_x_off}" y_off="${camera_y_off}" z_off="${camera_z_off}"/>
  </xacro:macro>
</robot>
