version: "3.9"

x-base: &base
  network_mode: "host"
  restart: always

x-environment: &environment
  ROS_DOMAIN_ID: 104

services:
  rover0:
    <<: *base
    image: rover0/rover0
    build:
      context: src/rover0
    container_name: rover0
    environment:
      <<: *environment
        #command: ros2 launch rosbot_bringup bringup.launch.py
    command: tail -f /dev/null

  teleop:
    <<: *base
    image: rover0/teleop
    build:
      context: src/teleop
    container_name: teleop
    volumes:
      - /run/udev
    devices:
      - /dev/dma_heap
      - /dev/media0
      - /dev/media1
      - /dev/media2
      - /dev/media3
      - /dev/media4
      - /dev/v4l-subdev0
      - /dev/video0
      - /dev/video10
      - /dev/video11
      - /dev/video12
      - /dev/video13
      - /dev/video14
      - /dev/video15
      - /dev/video16
      - /dev/video18
      - /dev/video19
      - /dev/video20
      - /dev/video21
      - /dev/video22
      - /dev/video23
      - /dev/video31
    environment:
      <<: *environment
    command: tail -f /dev/null

  uros-agent-lidar:
    <<: *base
    image: microros/micro-ros-agent:jazzy
    container_name: uros-agent-lidar
    devices:
      - ${LIDAR_SERIAL_PORT:?err}
    environment:
      <<: *environment
    command: serial -D $LIDAR_SERIAL_PORT serial -b 115200 -v1
