version: "3.9"

x-base: &base
  restart: always

x-environment: &environment
  ENV: "dev"
  ROS_DOMAIN_ID: 104

services:
  rover0:
    <<: *base
    image: rover0/rover0
    build:
      context: modules/rover0
    container_name: rover0
    ipc: host
    volumes:
      - /run/udev
      - ./modules:/modules
    working_dir: /modules/rover0
    environment:
      <<: *environment
  teleop:
    <<: *base
    image: rover0/teleop
    build:
      context: modules/teleop
    container_name: teleop
    ipc: host
    volumes:
      - /run/udev
      - ./modules:/modules
    devices:
      - /dev/dma_heap/linux,cma
      - /dev/dma_heap/system
      - /dev/media0
      - /dev/media1
      - /dev/media2
      - /dev/media3
      - /dev/media4
      - /dev/v4l-subdev0
      - /dev/video0
      - /dev/video10
      - /dev/video11
      - /dev/video12
      - /dev/video13
      - /dev/video14
      - /dev/video15
      - /dev/video16
      - /dev/video18
      - /dev/video19
      - /dev/video20
      - /dev/video21
      - /dev/video22
      - /dev/video23
      - /dev/video31
      - ${MOTOR_SERIAL_PORT:?err}
    ports:
      - "${FOXGLOVE_WS_PORT:-8765}:${FOXGLOVE_WS_PORT:-8765}"
    working_dir: /modules/teleop
    environment:
      <<: *environment
      FOXGLOVE_WS_PORT: ${FOXGLOVE_WS_PORT:-8765}
  uros-agent-lidar:
    <<: *base
    image: rover0/uros-agent-lidar
    build:
      context: modules/uros-agent-lidar
    container_name: uros-agent-lidar
    ipc: host
    volumes:
      - ./modules:/modules
    working_dir: /modules/uros-agent-lidar/
    devices:
      - ${LIDAR_SERIAL_PORT:?err}
    environment:
      <<: *environment
    command: serial -D $LIDAR_SERIAL_PORT serial -b 230400 -v1
