controller_manager:
    ros__parameters:
        update_rate: 50
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster
        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster
        rover0_controller:
            type: rover0_controller/Rover0Controller

imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: "imu_sensor"
        frame_id: "imu_link"
        static_covariance_linear_acceleration:
            - 1.168703278153771e-05
            - 0.0
            - 0.0
            - 0.0
            - 1.103400517532549e-05
            - 0.0
            - 0.0
            - 0.0
            - 2.3499370797708252e-05
        static_covariance_angular_velocity:
            - 0.009689936178965297
            - 0.0
            - 0.0
            - 0.0
            - 0.015205154655327513
            - 0.0
            - 0.0
            - 0.0
            - 0.011295287760670902

joint_state_broadcaster:
    ros__parameters:
        update_rate: 10

rover0_controller:
    ros__parameters:
        update_rate: 10
        front_left_wheel_joint_name: "front_left_wheel_joint"
        front_right_wheel_joint_name: "front_right_wheel_joint"
        rear_left_wheel_joint_name: "rear_left_wheel_joint"
        rear_right_wheel_joint_name: "rear_right_wheel_joint"
        wheel_radius: 0.028
        wheelbase: 0.14
        track_width: 0.11
