slam_toolbox_node:
    ros__parameters:
        mode: "mapping"
        map_update_interval: 1.0
        odom_frame: odom
        map_frame: map
        base_frame: base_link
        scan_topic: /scan
        resolution: 0.05
        max_laser_range: 6.0
          #        mode: asynchronous
