version: "3.9"

x-base: &base
  network_mode: "host"
  restart: always

x-environment: &environment
  ROS_DOMAIN_ID: 104

services:
  ros2:
    <<: *base
    image: rover0/ros2
    container_name: main
        #command: ros2 launch rosbot_bringup bringup.launch.py
    environment:
      <<: *environment
    command: tail -f /dev/null
  uros-agent-lidar:
    <<: *base
    image: microros/micro-ros-agent:humble
    container_name: uros-agent-lidar
    devices:
      - ${LIDAR_SERIAL_PORT:?err}
    environment:
      <<: *environment
    command: serial -D $LIDAR_SERIAL_PORT serial -b 115200
  uros-agent-motor:
    <<: *base
    image: microros/micro-ros-agent:humble
    container_name: uros-agent-motor
    devices:
      - ${MOTOR_SERIAL_PORT:?err}
    environment:
      <<: *environment
    command: serial -D $MOTOR_SERIAL_PORT serial -b 115200
