<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find rover0_description)/urdf/rover0_description_lidar.urdf.xacro" />

    <xacro:macro name="gz_lidar" params="reference frame_id topic base_height x_off">
        <gazebo reference="${reference}">
            <sensor name="lidar" type="gpu_lidar">
                <always_on>true</always_on>
                <visualize>true</visualize>
                <update_rate>1</update_rate>
                <gz_frame_id>${frame_id}</gz_frame_id>
                <topic>${topic}</topic>
                <pose>${x_off} 0 ${mount_height + (base_height + lidar_height) / 2} 0 0 0</pose>
                <lidar>
                    <scan>
                        <horizontal>
                            <samples>360</samples>
                            <resolution>1.0</resolution>
                            <min_angle>0.00</min_angle>
                            <max_angle>6.28</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.12</min>
                        <max>5.0</max>
                        <resolution>0.015</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </lidar>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>
