version: "3.9"

services:
  calibrate_imu_init:
    build:
      context: .
      dockerfile: Dockerfile
    image: rover0/calibrate_imu
    container_name: calibrate_imu_init
    command: poetry install 
    volumes:
      - .:/workspace
    working_dir: /workspace
  calibrate_imu:
    image: rover0/calibrate_imu
    container_name: calibrate_imu
    command: poetry run python calibrate_imu/main.py ${MOTOR_SERIAL_PORT:?err}
    devices:
      - ${MOTOR_SERIAL_PORT:?err}
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
