name: Test Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [rover0, teleop, uros-agent-lidar]
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build image (without pushing)
      uses: docker/build-push-action@v4
      with:
        context: modules
        file: modules/${{ matrix.module }}/Dockerfile
        platforms: linux/amd64  # Build for amd64 first for testing
        push: false
        tags: rover0/${{ matrix.module }}:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test ARM64 build
      uses: docker/build-push-action@v4
      continue-on-error: true  # Don't fail the workflow if ARM64 build fails
      with:
        context: modules
        file: modules/${{ matrix.module }}/Dockerfile
        platforms: linux/arm64
        push: false
        tags: rover0/${{ matrix.module }}:test-arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max